### DISCUSSION TITLE
`inode` column

### DISCUSSION THREAD

**Discussion by goyalyashpal** [doublecmd/doublecmd#1801] [Suggestions]
### version:

```yaml
Double Commander
Version: 1.1.14 gamma
Revision: Unknown
Commit: Unknown
Build date: 2024/08/03
Lazarus: 3.2.0.0
FPC: 3.2.2
Platform: x86_64-Linux-qt5
OS version: NixOS 24.05 (Uakari)

Widgetset library: Qt 5.15.14, libQt5Pas 5.6.1
```

### description

* i wanted to see the `inode` info about the files to see which files are linked-hard together
* i.e. sort of manual-eyeballing equivalent of `find -samefile` filter
* but i see no such item under "Field contents", neither in DC, nor in plugins

the only ones available were:
* NAME, EXTension, PATH, NAMENOEXT, TYPE
* SIZE, LINKTO, COMPRESSEDSIZE
* ATTRibutes, OWNER, GROUP
* mod TIME, CREATION, ACCESS, CHANGE
* COMMENT
